$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: model
command: >-
  python 
  model/train.py
  --training_data {{inputs.training_data}}  --reg_rate {{inputs.reg_rate}}
inputs:
  training_data: 
    path: azureml:diabetes-prod-folder:latest
  reg_rate: 0.01
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
compute: "aml-mlops-prod"
experiment_name: "diabetes-detector"
description: "A job to train a logistic regression for diabetes dectection in production."